In [1]:
import pandas as pd

In [20]:
#Pixel-wise dataset splits
input_path = r"C:\Users\giova\OneDrive\Desktop\ZEULI\dataset\dataset.csv"

test_2 = [59, 60, 141, 142, 146, 147]

test_3 = [59, 60, 141, 142, 146, 147]
val_3 = [32, 33, 34, 35, 136, 137]
train_3 = [36, 37, 41, 42, 43, 44, 45, 46, 145, 51, 52, 53, 54, 148]

test_4 = [51, 59, 36, 37, 32, 33]
val_4 = [53, 60, 41, 42, 34, 35]
train_4 = [54, 148, 141, 142, 146, 147, 43, 44, 45, 145, 137, 136]

#1- random_split

df_trainval_1=dataset.sample(frac=0.8,random_state=42)
df_test_1=dataset.drop(df_trainval_1.index)
df_train_1 = df_trainval_1.sample(frac=0.8,random_state=42)
df_val_1 = df_trainval_1.drop(df_train_1.index)
df_test_1.to_csv(r'C:\Users\giova\OneDrive\Desktop\ZEULI\dataset\1- random_split\test_set_1.csv')
df_val_1.to_csv(r'C:\Users\giova\OneDrive\Desktop\ZEULI\dataset\1- random_split\val_set_1.csv')
df_train_1.to_csv(r'C:\Users\giova\OneDrive\Desktop\ZEULI\dataset\1- random_split\train_set_1.csv')

#2- test + random_split

df_test_2 = dataset[dataset['ID_Albero'].isin(test_2)]
df_trainval_2=dataset.drop(df_test_2.index)
df_train_2 = df_trainval_2.sample(frac=0.8,random_state=42)
df_val_2 = df_trainval_2.drop(df_train_2.index)
df_test_2.to_csv(r'C:\Users\giova\OneDrive\Desktop\ZEULI\dataset\2- test+random_split\test_set_2.csv')
df_val_2.to_csv(r'C:\Users\giova\OneDrive\Desktop\ZEULI\dataset\2- test+random_split\val_set_2.csv')
df_train_2.to_csv(r'C:\Users\giova\OneDrive\Desktop\ZEULI\dataset\2- test+random_split\train_set_2.csv')

#3- test + val + train

df_test_3 = dataset[dataset['ID_Albero'].isin(test_3)]
df_val_3 = dataset[dataset['ID_Albero'].isin(val_3)]
df_train_3 = dataset[dataset['ID_Albero'].isin(train_3)]
df_test_3.to_csv(r'C:\Users\giova\OneDrive\Desktop\ZEULI\dataset\3- test+val+train\test_set_3.csv')
df_val_3.to_csv(r'C:\Users\giova\OneDrive\Desktop\ZEULI\dataset\3- test+val+train\val_set_3.csv')
df_train_3.to_csv(r'C:\Users\giova\OneDrive\Desktop\ZEULI\dataset\3- test+val+train\train_set_3.csv')

#3- test + val + train

df_test_4 = dataset[dataset['ID_Albero'].isin(test_4)]
df_val_4 = dataset[dataset['ID_Albero'].isin(val_4)]
df_train_4 = dataset[dataset['ID_Albero'].isin(train_4)]
df_test_4.to_csv(r'C:\Users\giova\OneDrive\Desktop\ZEULI\dataset\4- even_clusters\test_set_4.csv')
df_val_4.to_csv(r'C:\Users\giova\OneDrive\Desktop\ZEULI\dataset\4- even_clusters\val_set_4.csv')
df_train_4.to_csv(r'C:\Users\giova\OneDrive\Desktop\ZEULI\dataset\4- even_clusters\train_set_4.csv')

In [30]:
#Tree-wise dataset splits
input_path = r"C:\Users\giova\OneDrive\Desktop\ZEULI\dataset\Tree_wise_median\dataset_tree_wise_median.csv"

test_2 = [59, 60, 141, 142, 146, 147]

test_3 = [59, 60, 141, 142, 146, 147]
val_3 = [32, 33, 34, 35, 136, 137]
train_3 = [36, 37, 41, 42, 43, 44, 45, 46, 145, 51, 52, 53, 54, 148]

test_4 = [51, 59, 36, 37, 32, 33]
val_4 = [53, 60, 41, 42, 34, 35]
train_4 = [54, 148, 141, 142, 146, 147, 43, 44, 45, 145, 137, 136]

#1- random_split

df_trainval_1=dataset.sample(frac=0.8,random_state=42)
df_test_1=dataset.drop(df_trainval_1.index)
df_train_1 = df_trainval_1.sample(frac=0.8,random_state=42)
df_val_1 = df_trainval_1.drop(df_train_1.index)
df_test_1.to_csv(r'C:\Users\giova\OneDrive\Desktop\ZEULI\dataset\1- random_split\test_set_1.csv')
df_val_1.to_csv(r'C:\Users\giova\OneDrive\Desktop\ZEULI\dataset\1- random_split\val_set_1.csv')
df_train_1.to_csv(r'C:\Users\giova\OneDrive\Desktop\ZEULI\dataset\1- random_split\train_set_1.csv')

#2- test + random_split

df_test_2 = dataset[dataset['ID_Albero'].isin(test_2)]
df_trainval_2=dataset.drop(df_test_2.index)
df_train_2 = df_trainval_2.sample(frac=0.8,random_state=42)
df_val_2 = df_trainval_2.drop(df_train_2.index)
df_test_2.to_csv(r'C:\Users\giova\OneDrive\Desktop\ZEULI\dataset\2- test+random_split\test_set_2.csv')
df_val_2.to_csv(r'C:\Users\giova\OneDrive\Desktop\ZEULI\dataset\2- test+random_split\val_set_2.csv')
df_train_2.to_csv(r'C:\Users\giova\OneDrive\Desktop\ZEULI\dataset\2- test+random_split\train_set_2.csv')

#3- test + val + train

df_test_3 = dataset[dataset['ID_Albero'].isin(test_3)]
df_val_3 = dataset[dataset['ID_Albero'].isin(val_3)]
df_train_3 = dataset[dataset['ID_Albero'].isin(train_3)]
df_test_3.to_csv(r'C:\Users\giova\OneDrive\Desktop\ZEULI\dataset\3- test+val+train\test_set_3.csv')
df_val_3.to_csv(r'C:\Users\giova\OneDrive\Desktop\ZEULI\dataset\3- test+val+train\val_set_3.csv')
df_train_3.to_csv(r'C:\Users\giova\OneDrive\Desktop\ZEULI\dataset\3- test+val+train\train_set_3.csv')

#3- test + val + train

df_test_4 = dataset[dataset['ID_Albero'].isin(test_4)]
df_val_4 = dataset[dataset['ID_Albero'].isin(val_4)]
df_train_4 = dataset[dataset['ID_Albero'].isin(train_4)]
df_test_4.to_csv(r'C:\Users\giova\OneDrive\Desktop\ZEULI\dataset\4- even_clusters\test_set_4.csv')
df_val_4.to_csv(r'C:\Users\giova\OneDrive\Desktop\ZEULI\dataset\4- even_clusters\val_set_4.csv')
df_train_4.to_csv(r'C:\Users\giova\OneDrive\Desktop\ZEULI\dataset\4- even_clusters\train_set_4.csv')

(109948, 21)
(51822, 21)
(78000, 21)

In [19]:
#train/val/test split per approccio pixelwise

ddd = pd.read_csv(r"C:\Users\giova\OneDrive\Desktop\ZEULI\dataset\Pixel_wise\dataset_pixel_wise.csv")
train = [32, 33, 34, 35, 136, 137, 36, 37, 41, 42, 43, 44, 45, 46, 145]
val = [51, 53, 54, 148]
test = [59, 60, 141, 142, 146, 147]
df_test = ddd[ddd['ID_Albero'].isin(test)].reset_index(drop=True)
df_val = ddd[ddd['ID_Albero'].isin(val)].reset_index(drop=True)
df_train = ddd[ddd['ID_Albero'].isin(train)].reset_index(drop=True)
tr = df_train.drop(['Unnamed: 0', 'ID', 'ID_Pixel', 'ID_Albero', 'UTM_lon', 'UTM_lat', 'NDVI'], axis=1)
v = df_val.drop(['Unnamed: 0','ID', 'ID_Pixel', 'ID_Albero', 'UTM_lon', 'UTM_lat', 'NDVI'], axis=1)
tst = df_test.drop(['Unnamed: 0', 'ID', 'ID_Pixel', 'ID_Albero', 'UTM_lon', 'UTM_lat', 'NDVI'], axis=1)
print(tr.shape)
print(v.shape)
print(tst.shape)
tr.to_csv(r"C:\Users\giova\OneDrive\Desktop\projects\SWP-regr\data\pixelwise\px_train_set.csv", index=False)
v.to_csv(r"C:\Users\giova\OneDrive\Desktop\projects\SWP-regr\data\pixelwise\px_val_set.csv", index=False)
tst.to_csv(r"C:\Users\giova\OneDrive\Desktop\projects\SWP-regr\data\pixelwise\px_test_set.csv", index=False)

(154396, 14)
(48552, 14)
(43730, 14)

In [18]:
tst

,Blue-444,Blue,Green-531,Green,NIR,Red-650,Rededge-705,Rededge-740,Rededge,Red,Temp,TEMP ARIA,UMID ARIA,SWP
0,19871,19455,27678,24169,23231,16703,25740,16530,24993,15466,39.683270,35.4,40.6,4.0
1,17240,18666,27079,22861,27725,17447,23190,18955,26898,17761,39.761429,35.4,40.6,4.0
2,20551,20422,27190,25010,26596,18132,22997,22740,29572,17562,39.900127,35.4,40.6,4.0
3,22363,22979,29271,27786,25915,17173,25099,22718,29923,16311,38.985794,35.4,40.6,4.0
4,21911,22579,28616,29479,28439,16016,24645,22816,30514,15974,38.988670,35.4,40.6,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43725,33148,27853,28475,32842,42214,33826,26752,41711,46449,17421,51.383881,33.5,37.7,13.0
43726,32787,22670,28103,34071,40815,30858,25174,41831,46741,19556,52.898170,33.5,37.7,13.0
43727,33878,31633,33180,32877,44458,34083,32586,36914,42564,25274,51.779484,33.5,37.7,13.0
43728,35361,29500,30419,33282,42663,34321,29290,38308,42314,19689,52.955444,33.5,37.7,13.0
43729,33050,24579,30883,35140,39372,32124,28374,40429,42363,20160,54.131401,33.5,37.7,13.0