In [1]:
from osgeo import gdal
import sentinelhub as sh
from sentinelhub import CRS
import rasterio
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
input_folder = r"C:\Users\giova\OneDrive\Desktop\ZEULI"
input_path = input_folder + "\\UNICO_ZEULI_OLIVO.xlsx"
output_path = input_folder + "\\ZEULI_OLIVO_UTM_220623.xlsx"
data_volo = "2022-06-23"

In [10]:
#Apre foglio excel in un dataframe
df = pd.read_excel(input_path, header=1)
#print(df)
df_day = df[df["DATA  RILIEVO"] == data_volo]
#print(df[["LONGITUDINE", "LATITUDINE"]])
print(df_day[["LONGITUDINE", "LATITUDINE", "ID"]])

     LONGITUDINE  LATITUDINE   ID
90     16.198634   41.240265   31
91     16.198712   41.240348   32
92     16.198625   41.240438   33
93     16.198615   41.240596   34
94     16.198690   41.240753   35
95     16.192928   41.239752   36
96     16.192811   41.239655   37
97     16.192678   41.240116   41
98     16.192963   41.240181   42
99     16.192775   41.240217   43
100    16.192894   41.240327   44
101    16.192770   41.240511   45
102    16.192884   41.240607   46
103    16.190536   41.234991   51
104    16.190393   41.234906   52
105    16.190311   41.235081   53
106    16.190821   41.234821   54
107    16.191038   41.236320   59
108    16.191030   41.236224   60
109    16.198782   41.240512  136
110    16.198884   41.240593  137
111    16.191125   41.236701  141
112    16.191120   41.236809  142
113    16.192651   41.240313  145
114    16.191164   41.236120  146
115    16.190921   41.236020  147
116    16.190641   41.234707  148

In [11]:
#CRS delle immagini
target_crs = CRS.UTM_33N
#CRS standard lon/lat
source_crs = CRS.WGS84

In [12]:
# conversione punti da lon/lat in source_crs a UTM in target_crs
utm_coords = []
for lon, lat, id in zip(df_day['LONGITUDINE'], df_day['LATITUDINE'], df_day['ID']):
    east, north = sh.transform_point((lon, lat), source_crs, target_crs)
    utm_coords.append((east,north,id))

utm_coords
utm_df = pd.DataFrame(utm_coords, columns = ['UTM_lon', 'UTM_lat', 'ID'])
utm_df

          UTM_lon       UTM_lat   ID
0   600440.974716  4.566122e+06   31
1   600447.383844  4.566131e+06   32
2   600439.955630  4.566141e+06   33
3   600438.875718  4.566159e+06   34
4   600444.920103  4.566176e+06   35
5   599963.606182  4.566058e+06   36
6   599953.949571  4.566048e+06   37
7   599942.101965  4.566099e+06   41
8   599965.885333  4.566106e+06   42
9   599950.076470  4.566110e+06   43
10  599959.880785  4.566122e+06   44
11  599949.209494  4.566143e+06   45
12  599958.616112  4.566153e+06   46
13  599770.400901  4.565527e+06   51
14  599758.546101  4.565518e+06   52
15  599751.408040  4.565537e+06   53
16  599794.543781  4.565509e+06   54
17  599810.448826  4.565675e+06   59
18  599809.924459  4.565665e+06   60
19  600452.998526  4.566150e+06  136
20  600461.421814  4.566159e+06  137
21  599817.159964  4.565718e+06  141
22  599816.576625  4.565730e+06  142
23  599939.539269  4.566120e+06  145
24  599821.312300  4.565653e+06  146
25  599801.100276  4.565642e+06  147
26  599779.632306  4.565496e+06  148

In [13]:
df_day = pd.merge(df_day, utm_df, on='ID')
df_day

,DATA RILIEVO,ID,CLUSTER,Long DSM,Lat DSM,LONGITUDINE,LATITUDINE,PRI530,PRI590,PRI,...,TEMP_FOGLIA,TIME,fenologia,htot(m),hpunto inserzione(m),d sotto punto ins (m),d max chioma (m),d ortogonale chioma (m),UTM_lon,UTM_lat
0,2022-06-23,31,0,"16° 11'55.08""","41° 14'24.95""",16.198634,41.240265,1468.000000,1484.333333,-0.005532,...,32.600,09:02:00,75,5.1,1.64,0.282,5.05,5.3,600440.974716,4.566122e+06
1,2022-06-23,32,0,"16° 11'55.36""","41° 14'25.25""",16.198712,41.240348,1389.000000,1412.666667,-0.008447,...,33.100,09:08:00,75,5.3,1.23,0.32,6.3,6,600447.383844,4.566131e+06
2,2022-06-23,33,0,"16° 11'55.04""","41° 14'25.57""",16.198625,41.240438,1353.666667,1761.333333,-0.130872,...,33.300,09:13:00,75,5.3,1.85,0.31,5.3,4.8,600439.955630,4.566141e+06
3,2022-06-23,34,0,"16° 11'55.01""","41° 14'26.14""",16.198615,41.240596,1433.666667,1487.000000,-0.018261,...,34.300,09:23:00,75,5.1,1.69,0.31,6.8,6.4,600438.875718,4.566159e+06
4,2022-06-23,35,0,"16° 11'55.28""","41° 14'26.71""",16.198690,41.240753,1502.333333,1537.333333,-0.011514,...,34.050,09:29:00,75,5.4,1.57,0.39,6.5,5.8,600444.920103,4.566176e+06
5,2022-06-23,36,0,"16° 11'34.53""","41° 14'23.10""",16.192928,41.239752,1266.333333,1304.333333,-0.014782,...,36.400,12:42:00,75,6.1,1.4,0.59,7.5,7.2,599963.606182,4.566058e+06
6,2022-06-23,37,0,"16° 11'34.11""","41° 14'22.75""",16.192811,41.239655,1245.333333,1264.000000,-0.007439,...,36.100,12:47:00,75,5.5,1.46,0.43,6.5,6.4,599953.949571,4.566048e+06
7,2022-06-23,41,1,"16° 11'33.63""","41° 14'24.41""",16.192678,41.240116,1319.666667,1338.666667,-0.007147,...,36.500,12:29:00,75,3.8,1.37,0.5,6.9,6.4,599942.101965,4.566099e+06
8,2022-06-23,42,1,"16° 11'34.66""","41° 14'24.65""",16.192963,41.240181,1340.000000,1418.666667,-0.028516,...,36.150,12:02:00,75,4,0.97,0.22,4.3,4.1,599965.885333,4.566106e+06
9,2022-06-23,43,1,"16° 11'33.99""","41° 14'24.78""",16.192775,41.240217,1250.666667,1279.333333,-0.011331,...,36.000,12:38:00,75,4.7,1.23,0.48,6.5,6.2,599950.076470,4.566110e+06
10,2022-06-23,44,1,"16° 11'34.41""","41° 14'25.17""",16.192894,41.240327,5882.000000,1384.666667,0.618899,...,37.495,12:15:00,75,3.7,1.5,0.325,6,4.6,599959.880785,4.566122e+06
11,2022-06-23,45,1,"16° 11'33.97""","41° 14'25.83""",16.192770,41.240511,1351.333333,1389.666667,-0.013985,...,37.250,12:23:00,75,4.8,1.02,0.44,5.6,5.2,599949.209494,4.566143e+06
12,2022-06-23,46,1,"16° 11'34.38""","41° 14'26.18""",16.192884,41.240607,1290.333333,1336.666667,-0.017637,...,37.150,12:18:00,75,4.9,1.42,0.48,5.1,4.7,599958.616112,4.566153e+06
13,2022-06-23,51,2,"16° 11'25.92""","41° 14'5.967""",16.190536,41.234991,1224.666667,1260.666667,-0.014485,...,35.150,13:20:00,75,5.7,1.55,0.42,6.4,5.8,599770.400901,4.565527e+06
14,2022-06-23,52,2,"16° 11'25.41""","41° 14'5.660""",16.190393,41.234906,1190.333333,1207.000000,-0.006952,...,35.250,13:27:00,75,5.3,1.13,0.95,6.4,5.3,599758.546101,4.565518e+06
15,2022-06-23,53,2,"16° 11'25.12""","41° 14'6.292""",16.190311,41.235081,1192.000000,1247.000000,-0.022550,...,34.900,13:23:00,75,5.5,1.57,0.69,6.8,5.8,599751.408040,4.565537e+06
16,2022-06-23,54,2,"16° 11'26.95""","41° 14'5.355""",16.190821,41.234821,1171.333333,1196.333333,-0.010559,...,37.250,13:35:00,75,5.1,1.8,0.48,5.1,5,599794.543781,4.565509e+06
17,2022-06-23,59,2,"16° 11'27.73""","41° 14'10.75""",16.191038,41.236320,1200.666667,1238.000000,-0.015309,...,34.700,13:06:00,75,4.6,1.05,0.212,5,4.6,599810.448826,4.565675e+06
18,2022-06-23,60,2,"16° 11'27.70""","41° 14'10.40""",16.191030,41.236224,1294.000000,1315.666667,-0.008302,...,34.150,13:09:00,75,5.1,1.5,0.45,5.55,5.25,599809.924459,4.565665e+06
19,2022-06-23,136,0,"16° 11'55.61""","41° 14'25.84""",16.198782,41.240512,1351.000000,1378.666667,-0.010136,...,33.550,09:16:00,75,5,1.15,0.335,6.8,6.7,600452.998526,4.566150e+06
20,2022-06-23,137,0,"16° 11'55.98""","41° 14'26.13""",16.198884,41.240593,1431.333333,1462.000000,-0.010599,...,33.850,09:22:00,75,5.5,1.2,0.34,7.1,6.6,600461.421814,4.566159e+06
21,2022-06-23,141,1,"16° 11'28.05""","41° 14'12.12""",16.191125,41.236701,1287.666667,1342.000000,-0.020662,...,34.900,13:02:00,75,4,0.87,0.152,4.4,4,599817.159964,4.565718e+06
22,2022-06-23,142,1,"16° 11'28.03""","41° 14'12.51""",16.191120,41.236809,1227.666667,1255.333333,-0.011142,...,34.950,13:01:00,75,5,1.21,0.29,5.8,5.6,599816.576625,4.565730e+06
23,2022-06-23,145,1,"16° 11'33.54""","41° 14'25.12""",16.192651,41.240313,1333.000000,1398.333333,-0.023920,...,38.350,12:26:00,75,4.8,1.34,0.62,6.3,6.1,599939.539269,4.566120e+06
24,2022-06-23,146,2,"16° 11'28.19""","41° 14'10.03""",16.191164,41.236120,1224.000000,1240.333333,-0.006628,...,35.000,13:13:00,75,5.5,1.18,0.31,5.7,5.5,599821.312300,4.565653e+06
25,2022-06-23,147,2,"16° 11'27.31""","41° 14'9.670""",16.190921,41.236020,1167.666667,1227.000000,-0.024777,...,35.450,13:16:00,75,5.5,1.11,0.55,6.1,5.6,599801.100276,4.565642e+06
26,2022-06-23,148,2,"16° 11'26.30""","41° 14'4.946""",16.190641,41.234707,1209.333333,1224.666667,-0.006300,...,34.800,13:31:00,75,6.3,1.73,0.87,7.3,6.2,599779.632306,4.565496e+06

In [14]:
# Seleziona solo le colonne desiderate nell'ordine specificato
df_new = df_day[['DATA  RILIEVO', 'ID', 'LONGITUDINE', 'LATITUDINE', 'UTM_lon', 'UTM_lat', 'TEMP ARIA', 'UMID ARIA', 'SWP']]

df_new.loc[:, 'TEMP ARIA'] = pd.to_numeric(df_new['TEMP ARIA'], errors='coerce')
df_new = df_new.dropna(subset=['TEMP ARIA'])
df_new.loc[:, 'UMID ARIA'] = pd.to_numeric(df_new['UMID ARIA'], errors='coerce')
df_new = df_new.dropna(subset=['UMID ARIA'])
df_new.loc[:, 'SWP'] = pd.to_numeric(df_new['SWP'], errors='coerce')
df_new = df_new.dropna(subset=['SWP'])

df_new['DATA  RILIEVO'] = pd.to_datetime(df_new['DATA  RILIEVO'])
df_new['DATA  RILIEVO'] = df_new['DATA  RILIEVO'].dt.date

# Stampa del nuovo DataFrame
print(df_new)

   DATA  RILIEVO   ID  LONGITUDINE  LATITUDINE        UTM_lon       UTM_lat  \
1     2022-06-23   32    16.198712   41.240348  600447.383844  4.566131e+06
2     2022-06-23   33    16.198625   41.240438  600439.955630  4.566141e+06
3     2022-06-23   34    16.198615   41.240596  600438.875718  4.566159e+06
4     2022-06-23   35    16.198690   41.240753  600444.920103  4.566176e+06
5     2022-06-23   36    16.192928   41.239752  599963.606182  4.566058e+06
6     2022-06-23   37    16.192811   41.239655  599953.949571  4.566048e+06
7     2022-06-23   41    16.192678   41.240116  599942.101965  4.566099e+06
8     2022-06-23   42    16.192963   41.240181  599965.885333  4.566106e+06
9     2022-06-23   43    16.192775   41.240217  599950.076470  4.566110e+06
10    2022-06-23   44    16.192894   41.240327  599959.880785  4.566122e+06
11    2022-06-23   45    16.192770   41.240511  599949.209494  4.566143e+06
12    2022-06-23   46    16.192884   41.240607  599958.616112  4.566153e+06
13    2022-06-23   51    16.190536   41.234991  599770.400901  4.565527e+06
15    2022-06-23   53    16.190311   41.235081  599751.408040  4.565537e+06
16    2022-06-23   54    16.190821   41.234821  599794.543781  4.565509e+06
17    2022-06-23   59    16.191038   41.236320  599810.448826  4.565675e+06
18    2022-06-23   60    16.191030   41.236224  599809.924459  4.565665e+06
19    2022-06-23  136    16.198782   41.240512  600452.998526  4.566150e+06
20    2022-06-23  137    16.198884   41.240593  600461.421814  4.566159e+06
21    2022-06-23  141    16.191125   41.236701  599817.159964  4.565718e+06
22    2022-06-23  142    16.191120   41.236809  599816.576625  4.565730e+06
23    2022-06-23  145    16.192651   41.240313  599939.539269  4.566120e+06
24    2022-06-23  146    16.191164   41.236120  599821.312300  4.565653e+06
25    2022-06-23  147    16.190921   41.236020  599801.100276  4.565642e+06
26    2022-06-23  148    16.190641   41.234707  599779.632306  4.565496e+06

    TEMP ARIA UMID ARIA   SWP
1        35.3      23.8   8.8
2        36.1      23.8   9.0
3        35.7      26.7   4.2
4        34.6      25.4   5.2
5        36.3      40.1   9.0
6        35.8      45.5   8.4
7        37.9      37.1   8.8
8        37.6      37.7   6.0
9        36.4      39.2   8.8
10       37.2      40.1   9.4
11       38.5      36.5   9.6
12       38.1      36.4   6.0
13       34.7      41.8   9.0
15       34.5      40.8   2.0
16       34.7      41.9   6.0
17       35.2      41.8   9.0
18       34.8      39.6   8.0
19       36.0      23.8   9.0
20       35.2      24.6   8.2
21       35.4      40.6   4.0
22       35.1      40.7   8.6
23       35.4      38.9  10.0
24       36.1      39.7   9.4
25       36.4      38.5   7.4
26       36.1      40.7  13.0

In [15]:
df_new.to_excel(output_path, index=False)